export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const REGISTRATION = 'REGISTRATION'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'

export const GET_ALL_ROOMS_USER = 'GET_ALL_ROOMS_USER'
export const GET_ALL_ROOMS_USER_SUCCESS = 'GET_ALL_ROOMS_USER_SUCCESS'
export const GET_ALL_ROOMS_USER_ERROR = 'GET_ALL_ROOMS_USER_ERROR'

export const GET_ROOM_INFO = 'GET_ROOM_INFO'
export const GET_ROOM_INFO_SUCCESS = 'GET_ROOM_INFO_SUCCESS'
export const GET_ROOM_INFO_ERROR = 'GET_ROOM_INFO_ERROR'

export const WATER_INTERRUPTOR = 'WATER_INTERRUPTOR'
export const WATER_INTERRUPTOR_SUCCESS = 'WATER_INTERRUPTOR_SUCCESS'
export const WATER_INTERRUPTOR_ERROR = 'WATER_INTERRUPTOR_ERROR'