export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const REGISTRATION = 'REGISTRATION'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS'
export const REGISTRATION_ERROR = 'REGISTRATION_ERROR'

export const CREATE_ROOM = 'CREATE_ROOM'
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS'
export const CREATE_ROOM_ERROR = 'CREATE_ROOM_ERROR'

export const GET_ALL_ROOMS_USER = 'GET_ALL_ROOMS_USER'
export const GET_ALL_ROOMS_USER_SUCCESS = 'GET_ALL_ROOMS_USER_SUCCESS'
export const GET_ALL_ROOMS_USER_ERROR = 'GET_ALL_ROOMS_USER_ERROR'

export const GET_ROOM_INFO = 'GET_ROOM_INFO'
export const GET_ROOM_INFO_SUCCESS = 'GET_ROOM_INFO_SUCCESS'
export const GET_ROOM_INFO_ERROR = 'GET_ROOM_INFO_ERROR'

export const WATER_INTERRUPTOR = 'WATER_INTERRUPTOR'
export const WATER_INTERRUPTOR_SUCCESS = 'WATER_INTERRUPTOR_SUCCESS'
export const WATER_INTERRUPTOR_ERROR = 'WATER_INTERRUPTOR_ERROR'

export const CHANGE_SENSORS_DATA = 'CHANGE_SENSORS_DATA'

export const EDIT_ROOM = 'EDIT_ROOM'
export const EDIT_ROOM_SUCCESS = 'EDIT_ROOM_SUCCESS'
export const EDIT_ROOM_ERROR = 'EDIT_ROOM_ERROR'

export const DELETE_ROOM = 'DELETE_ROOM'
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS'
export const DELETE_ROOM_ERROR = 'DELETE_ROOM_ERROR'